### ISSUE TITLE
Blends visible through blends

### ISSUE THREAD

**Issue by thrownewexception** [Nukem9/LinkerMod#14]
Not sure whether this is an engine bug or not but http://prntscr.com/bg9n7q the plasma blend shows all other blends behind it regardless of the various depth settings in the asset manager.

**Comment by SE2Dev** [comment]
This may be a statemap or technique issue, are you sure those other materials aren't decals and not blends?

**Comment by thrownewexception** [comment]
The one on the wall is a punchout alpha test.

**Comment by thrownewexception** [comment]
Wall settings: http://prntscr.com/bgabpa, plasma http://prntscr.com/bgabt6 tried bunch of depth settings.

**Comment by SE2Dev** [comment]
No I meant, are you using them as decals or are you blending them like terrain?

Could you send the two material files (from raw\materials)?

**Comment by thrownewexception** [comment]
Just a regular decal, but they're set as blends in assman :) sure one second

**Comment by SE2Dev** [comment]
Try using the "effect" materialType in Asset Manager.

**Comment by thrownewexception** [comment]
For both or just one?

**Comment by SE2Dev** [comment]
Just for the plasma material.

**Comment by thrownewexception** [comment]
No change.

**Comment by thrownewexception** [comment]
Worked like a charm, feel free to close this unless you'd like it open.
