### ISSUE TITLE
Windows XP Compatibility Issues

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [Nukem9/LinkerMod#17]
I know that XP is outdated and no longer supported. But could you please make game_mod work with XP? Why in particular would I need XP? Well you see, I dunno why, but on my machine Black Ops 1 lags abnormally on all Windows NT 6.0+, on XP it runs fine (I just dunno why). Well, when I tried launching game_mod it just said that launcher_ldr.exe is not a Win32 application. So, if it's not hard, can you include Windows XP support?

**Comment by SE2Dev** [comment]
What are the specs of the machine? Also can you run launcher_ldr.exe by itself or does the error show up there as well?

**Comment by BuIlDaLiBlE** [comment]
Specs are listed there: [www.tenforums.com/members/buildalible.html](url)
I tried to opening launcher_ldr.exe by itself too, but it ends up giving the same error.

**Comment by SE2Dev** [comment]
Try replacing bin/game_mod.dll and bin/launcher_ldr.exe with the ones in the following zip archive.
www.se2dev.com/gm_xp.zip

**Comment by BuIlDaLiBlE** [comment]
That seems to be working. Thanks!
