### ISSUE TITLE
Possible to compile the menu_map_classified_mini.iwi in the FF instead

### ISSUE THREAD

**Issue by thrownewexception** [Nukem9/LinkerMod#2]
Would be one less file to deal with, correct me if this isn't possible.

**Comment by DidUknowiPwn** [comment]
You can't build images into fastfiles as images are streamed.

**Comment by SE2Dev** [comment]
Like DUKIP said images are streamed (loadd from *.iwd files) and therefore cant be compiled into a fastfile. iw_42.iwd however, only a single file, and doesn't really add any complications to the installation process (unless there is some sort of conflict with another file - in which case let me know).

**Comment by thrownewexception** [comment]
A lot of existing mods for black ops 1 use iw_42 as their base, I simply renamed the included one to iw_99.iwd to avoid this issue.

**Comment by SE2Dev** [comment]
Modifying existing game files is a bad idea in-general, but I'll check other names I suppose.

**Comment by DidUknowiPwn** [comment]
No point really just move those existing hack mods to proper mods.
