### ISSUE TITLE
Gibbing zombie model parts (heads, legs) causes the game to crash

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [Nukem9/LinkerMod#20]
Only happens when the player does it as far as I've noticed. Killing zombies in the body when insta-kill is active causes their heads to be gibbed, but that's the script doing it I presume so it doesn't crash the game. This also happens when you gib legs.
![image](https://cloud.githubusercontent.com/assets/12040085/17927494/98699c02-69fe-11e6-879a-aca1aa7c5006.png)
Steps to reproduce:
1. Launch the map
2. Shoot zombies with explosives or bullet weapons with enough damage to gib any part of the model

**Comment by SE2Dev** [comment]
Check the gib definition for your spawned gib models in asset manager. If I remember correctly it should be 'gib'.

**Comment by BuIlDaLiBlE** [comment]
Don't know for what to search honestly. I only converted these models:
![image](https://cloud.githubusercontent.com/assets/12040085/17989546/c79c4dec-6b36-11e6-88d7-a1c6eaf6e971.png)
Did I forget the gibs? Lime export folder only contains models starting from fx_char_gib. Are those correct?

**Comment by SE2Dev** [comment]
Essentially anything that ends with spawn (_rarmspawn, rlegspawn, llegspawn, etc.) is a _gib_ model. Not to be confused with _gibbed_ model which would be things like larmoff, etc.
Gib models: the hands and feet that spawn when you gib a zombie's limb.
Gibbed models: the models used by the zombies when they're missing a limb.

Essentially, open the GDT that lime spit out, and goto any of the _gib_ models, and set the physicsPreset to 'gib'.

**Comment by BuIlDaLiBlE** [comment]
That fixed the issue! Thanks, I would have never even guessed about that setting.
