### ISSUE TITLE
Can't get legacy mods to work.

### ISSUE THREAD

**Issue by Jbleezy** [Nukem9/LinkerMod#21]
I put "_override" at the end of the FF name, but it still does not load the mod at all.

**Comment by SE2Dev** [comment]
Can you provide a bit more info? What does the directory you've set up look like? What mod are you attempting to use? etc.

**Comment by Jbleezy** [comment]
I'm attempting to use my own mod. It works just fine if I replace the files manually. Here's the directory. https://gyazo.com/1dd65cf34ba34d7473f1ef29532a891d
![directory](https://cloud.githubusercontent.com/assets/20487224/19057929/5b0ca2a6-8988-11e6-8cc8-2dbf17921780.png)

**Comment by SE2Dev** [comment]
Are you using game_mod 1.0.0 or are you using 1.0.1?

**Comment by Jbleezy** [comment]
1.0.1

**Comment by SE2Dev** [comment]
Can you send me the package? I'm fairly certain it should work and don't really understand why it isn't.

**Comment by Jbleezy** [comment]
https://www.sendspace.com/file/ncgsyg

**Comment by Jbleezy** [comment]
Do you know what the problem could be?

**Comment by SE2Dev** [comment]
I'm not really sure why its not loading correctly, all of the steps that you listed are completely reproducible and have the same results that you said they had for you. The best advice I can offer for the time being is to recompile the mod as a normal mod.

**Comment by Jbleezy** [comment]
How exactly do you install linkermod?

**Comment by SE2Dev** [comment]
Put all of the compiled DLL's in /bin and open each tool with a command such as `launcher_ldr linker_pc.dll linker_pc.exe myargs`.

**Comment by Jbleezy** [comment]
I'm not sure if I'm opening it right. Could you explain with more detail?

**Comment by Jbleezy** [comment]
I finally got it working.

The problem was I was loading the mod without an IWD since I have only done scripting so far with my mod. Apparently you have to include the IWD no matter what, something you should add to the legacy mods tutorial.

Also, I was able to load the mod with and without the _override suffix, is that suppose to happen?

**Comment by SE2Dev** [comment]
> Also, I was able to load the mod with and without the _override suffix, is that suppose to happen?
Not really
> The problem was I was loading the mod without an IWD since I have only done scripting so far with my mod.
This doesn't really explain why Rollon's gun mod worked but your's didn't, though...

**Comment by Jbleezy** [comment]
I just did a test.
Deleted the IWD, didn't work again. Readded the IWD and then it works. It definitely was not having the IWD which caused the problem. It also still works with or without _override suffix. I don't know why mine is working differently but I'm glad I found a fix.

**Comment by SE2Dev** [comment]
When you say "with or without suffix" you mean "common_zombie_patch.ff" works too? Or did you mean "mod.ff"? Either way I'm not really sure why the issue was that it was missing an IWD...

**Comment by Jbleezy** [comment]
common_zombie_patch

**Comment by Jbleezy** [comment]
I realize now that my mod isn't a legacy mod, and just a normal game_mod mod...
