### ISSUE TITLE
mods not working

### ISSUE THREAD

**Issue by Itayrutigliano** [Nukem9/LinkerMod#22]
http://imgur.com/BFrQ5g6 as you can see i loaded fury's temple mod but when i try to play it nothing happens﻿

**Comment by SE2Dev** [comment]
When exactly does this occur? When you try to launch the map? When you open the "Custom Zombies" tab?

**Comment by Itayrutigliano** [comment]
Yes when i select the custom map and then it should start loading

**Comment by Itayrutigliano** [comment]
as you can see there is the gobblegum machine behind

**Comment by Itayrutigliano** [comment]
maybe if you can send me a custom test map i can try it to see if it works

**Comment by SE2Dev** [comment]
Try opening the Fury's Temple mod, then opening the console and entering `logfile 2`, then press Enter. Attempt to load the Fury's Temple map, then wait a few seconds, then open the console again and enter '/quit' and press Enter.

Then navigate to the Fury's Temple mod folder and send the `console.log` file.

**Comment by Itayrutigliano** [comment]
here

**Comment by Itayrutigliano** [comment]
[console.zip](https://github.com/Nukem9/LinkerMod/files/511950/console.zip)

**Comment by SE2Dev** [comment]
What happens if you try to launch Shangri-La normally, with Fury's Temple loaded?

**Comment by Itayrutigliano** [comment]
crashes

**Comment by Itayrutigliano** [comment]
with every map

**Comment by SE2Dev** [comment]
Does it do this even without any mods (other than game_mod itself) loaded? What is the error that it gives?

**Comment by Itayrutigliano** [comment]
nope i played nova six and griffin station

**Comment by Itayrutigliano** [comment]
the error is out of memory

**Comment by SE2Dev** [comment]
Just post a screenshot, its a million times easier knowing the *exact* string that gets displayed.

**Comment by Itayrutigliano** [comment]
no strings

**Comment by Itayrutigliano** [comment]
just "out of memory error. you are probably low on hard disk space"

**Comment by SE2Dev** [comment]
Are you *sure* you're using game_mod 1.0.1?

**Comment by Itayrutigliano** [comment]
im using 0.1

**Comment by Itayrutigliano** [comment]
1.0 and 1.0.1 doesnt even start

**Comment by SE2Dev** [comment]
Fury's Temple requires 1.0.0+ to run, its completely incompatible with 0.0.1.
1.0.x ones were giving you that [Fatal Error](http://imgur.com/a/elIBG) you showed before, correct?

**Comment by Itayrutigliano** [comment]
yep

**Comment by SE2Dev** [comment]
Can you send me your BlackOps.exe file?

**Comment by Itayrutigliano** [comment]
[Uploading BlackOps.zip…]()

**Comment by Itayrutigliano** [comment]
[BlackOps.zip](https://github.com/Nukem9/LinkerMod/files/512096/BlackOps.zip)

**Comment by Itayrutigliano** [comment]
sorry didnt mean to close it

**Comment by SE2Dev** [comment]
Do you have any sort of custom patch installed, the EXE you have doesn't seem to match any of the ones I've seen before.

**Comment by Itayrutigliano** [comment]
So?

**Comment by SE2Dev** [comment]
"Do you have any sort of custom patch installed?"

**Comment by Itayrutigliano** [comment]
i dont think so

**Comment by SE2Dev** [comment]
https://steamcommunity.com/profiles/76561198181057434 is this your Steam Account?

**Comment by Itayrutigliano** [comment]
yep

**Comment by SE2Dev** [comment]
You don't own BO1 on that account...

**Comment by Itayrutigliano** [comment]
i dont have it on steam...

**Comment by Itayrutigliano** [comment]
no prob i'm buying it now...

**Comment by Itayrutigliano** [comment]
do i need all dlc's ?

**Comment by Itayrutigliano** [comment]
do i need dlc's

**Comment by Itayrutigliano** [comment]
?

**Comment by SE2Dev** [comment]
You don't need the DLC's to use game_mod.
You *do* however need the First Strike DLC Pack for Project Thor, and the Annihilation DLC Pack for Fury's Temple.

**Comment by Itayrutigliano** [comment]
but for any future custom map do you think i need any dlc?

**Comment by SE2Dev** [comment]
It depends on what the mappers do, if they package DLC content in their map, and don't include the assets (sounds, images, etc.) with their mod, then you'd probably need the DLC that has the content they used.

**Comment by Itayrutigliano** [comment]
oh okay thank you for your patience =)
