### ISSUE TITLE
 C2371

### ISSUE THREAD

**Issue by WECoyote99** [Nukem9/LinkerMod#23]
So I got the new source code and when I go to build it, it gives that error for all except 4 don't know if it's a visual 2015 prob or not

**Comment by SE2Dev** [comment]
Can you post a piece of the compile log so we have a better idea of where the errors are occurring?

**Comment by WECoyote99** [comment]
https://gyazo.com/f362679c8734aa2950728b77140f1dca

**Comment by WECoyote99** [comment]
stdint.h is the file

**Comment by SE2Dev** [comment]
This sounds like it could be some sort of issue with your Visual Studio environment as @Nukem9 has been able to build the entire solution reliably in VS2015 for months.

**Comment by Nukem9** [comment]
`Typedef.h` has been removed.
