### ISSUE TITLE
Problems open "Game_Mod"

### ISSUE THREAD

**Issue by adreakos876** [Nukem9/LinkerMod#26]
Hi, my black ops 1, when I open the file "Bo_Mods" I get this, if someone could be so kind to help me, sorry for my bad English
![1f372ce6657557fbb2b8ed836f5a7ce2c66035de9c6b029ea1 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/24442094/20985695/507aba0e-bca4-11e6-9368-9012f692bb69.jpg)

**Comment by SE2Dev** [comment]
1: Are you using a legitimate copy of BO1 from Steam?
2: What version of Windows are you running?
3: That screencap appears to be in a resolution that's so low that I can't read the error. Do you have a better screencap?

**Comment by Arefu** [comment]
it looks like he is using Windows 8 (not 8.1) With non-legit Steam. As for error that's up to him
