### ISSUE TITLE
How to play CO-OP with my friend

### ISSUE THREAD

**Issue by JoKeRxPlayz** [Nukem9/LinkerMod#28]
i downloaded the game-modand its working 
 but how can i play co-op

**Comment by SE2Dev** [comment]
If you're referring to the co-op campaign, I never released the mod because it depends on some code that isn't available in the currently released version of game_mod.

**Comment by JoKeRxPlayz** [comment]
yes the campaign but
when u think it well be released



thx

2017-03-28 4:36 GMT+03:00 SE2Dev <notifications@github.com>:

**Comment by SE2Dev** [comment]
It is available here: http://se2dev.com/2017/06/black-ops-coop.html
