### ISSUE TITLE
Game Crashes 15 Minutes In

### ISSUE THREAD

**Issue by ComoSrgt** [Nukem9/LinkerMod#29]
Everytime I play a mod the game crashes 15 minutes into the game. I have tried everything in steam and in the game files I don't know what seems to be the problem. I'm using game_mod

**Comment by SE2Dev** [comment]
Can you elaborate at all? Do any error messages show up? Does it happen with every mod? Which mod / map / mode were you playing? Does it only happen when using game_mod? Which version of game_mod are you using? etc.

**Comment by Nukem9** [comment]
No response. Closed.
