### ISSUE TITLE
A TODO list and or make issues regarding what's next

### ISSUE THREAD

**Issue by thrownewexception** [Nukem9/LinkerMod#4]
If you're expecting people to make pulls it would be nice to know what needs to be done. As I've dug through most of the source it looks like reflections still need to be done, along with the setup process.

**Comment by SE2Dev** [comment]
It wasn't so much a matter of "expecting" people to make pulls, as it was packaging the assets needed for setup, fixing a few bugs, etc.

But I'll get started on an official todo list.

**Comment by thrownewexception** [comment]
Sounds good!
