### ISSUE TITLE
Error when attempting to Open Black Ops 1 with BO_Mods.bat

### ISSUE THREAD

**Issue by Meknife2000** [Nukem9/LinkerMod#54]
i'm not sure what's happening here but i keep getting an error when i try to open black ops using BO_Mods.bat, i've taken a screenshot of the error but i don't have any idea what it means.
![image](https://user-images.githubusercontent.com/41457237/42978735-8e326932-8b9c-11e8-9d4b-544debdd4b54.png)

**Comment by SE2Dev** [comment]
Cracks aren't supported.
