### ISSUE TITLE
Where am i supose to put the files?

### ISSUE THREAD

**Issue by m1cke1** [Nukem9/LinkerMod#6]
Where am i supose to put the files?

**Comment by SE2Dev** [comment]
Which files?

**Comment by m1cke1** [comment]
linker mod

**Comment by DidUknowiPwn** [comment]
https://www.youtube.com/watch?v=6_bwsiGpLVk

game_mod installation

**Comment by m1cke1** [comment]
yeah i know how to install that that goes in the root derectory but the Linker mod u know the Enchantment for mod tools

**Comment by SE2Dev** [comment]
Linker_Mod (as a whole) isn't complete yet, the installation files, steps, etc. are subject to change, etc.

There is no installation tutorial at the moment because Linker_Mod itself isn't complete yet.

**Comment by m1cke1** [comment]
so i cant install and make my own maps?

**Comment by SE2Dev** [comment]
Not _yet_.
