### ISSUE TITLE
When I open BO_Mods it instantly closes

### ISSUE THREAD

**Issue by CosmicX14** [Nukem9/LinkerMod#64]
I am not using a crack, and when I open it, with admin permissions, it just closes. I tried opening launcher_ldr directly, but that just ends in this:
![Steam error](https://user-images.githubusercontent.com/39860739/57193447-f589af80-6f32-11e9-89e4-9e9e5ff7f9a7.PNG)

**Comment by SE2Dev** [comment]
What happens if you run the batch file from an existing command prompt that has admin permissions?

**Comment by CosmicX14** [comment]
Problem fixed, I changed my PC permissions to administrator and it worked!

**Comment by SE2Dev** [comment]
I just want to make a note that the next version of game_mod shouldn't have this issue anymore.
