### ISSUE TITLE
Error starting batchfile

### ISSUE THREAD

**Issue by ibbenbueren99** [Nukem9/LinkerMod#69]
![bo1](https://user-images.githubusercontent.com/62486934/77237823-b6586180-6bcb-11ea-8639-716d73484a66.PNG)
i get this everytime. i have game_mod latest version. i dont get it

**Comment by SE2Dev** [comment]
The version of the game you’re using is not supported. I assume you’re using either the German version of the game, or a pirated copy. In either case, those versions of the game aren’t supported.

**Comment by ibbenbueren99** [comment]
I got fixed. Asked in discord server where other mod player are. I have steam Edition. Needed to replace BlackOps.exe with a English version of the. .exe works like a charm still ty for reply

**Comment by SE2Dev** [comment]
Cheers
