### ISSUE TITLE
Custom Maps Bo1

### ISSUE THREAD

**Issue by Arefu** [Nukem9/LinkerMod#7]
Hey, you say in the description that this launcher will allow us to load custom maps, but problem. You can't make maps for bo1?

**Comment by m1cke1** [comment]
apperently the radiant tool is not done yet so you cant YET

**Comment by thrownewexception** [comment]
The tools aren't ready and definitely not user friendly at the moment. Just wait a bit and the setup will be finished.

**Comment by m1cke1** [comment]
im so hyped for this dude got eny like relase date is it like over a month or a week

**Comment by SE2Dev** [comment]
Basically, whenever its ready.

**Comment by Arefu** [comment]
But the problem is Radiant for black ops 1 was never completed by Treyarch, they have been in Beta since they came out. 

Radiant for Bo3 wouldn't work in this engine. So are you making a community Radiant or something?

**Comment by SE2Dev** [comment]
Modified WAW radiant to work with BO1

**Comment by Arefu** [comment]
I know Radiant is usually open source, but how the damn did you manage to get it to work? I know they have open console to load maps, but seriously... How the bloody hell did you mange it.

Also where can I give you a donation for doing this?
