### ISSUE TITLE
Can't start game_mod

### ISSUE THREAD

**Issue by schneijan** [Nukem9/LinkerMod#70]
Hey,

I just downloaded the latest release (Game_Mod v1.3.2) after installing Visual Studio 2013 Redistributable, placed the files in the corresponding steam folder and exectued the bat file. As a result I got the following error message:

![image](https://user-images.githubusercontent.com/44969037/78361100-18e03300-75b8-11ea-8b45-906f01027672.png)

Any idea what could have gone wrong? Thanks in advance!

**Comment by SE2Dev** [comment]
See #69

**Comment by schneijan** [comment]
Thanks for your quick reply!
