### ISSUE TITLE
Infected download

### ISSUE THREAD

**Issue by inigofv** [Nukem9/LinkerMod#72]
I am new to Github and started having problems in my computer after downloading this file. After running it through VirusTotal I found the following. Any help?
![photo](https://user-images.githubusercontent.com/65270204/81770849-4ca35800-9496-11ea-82fb-1a5282240ed6.jpeg)

**Comment by SE2Dev** [comment]
Assuming you downloaded Game_Mod via this GitHub repository and don't already have some sort of issue with your computer, there should be no issues caused by Game_Mod. It *will*, however, show up on certain malware scanners since it injects code into the game process while it's running.

**Comment by Genreic-Gamer** [comment]
don't worry, it's pretty safe. I used virustotal and it said the exact same thing. But i threw caution into the wind and downloaded it. It turned out to be safe
