### ISSUE TITLE
Black screen and frozen when loading mod

### ISSUE THREAD

**Issue by 2bandz** [Nukem9/LinkerMod#76]
I load everything up correctly, but when i'm in black ops zombies, i go to mods, then i click a mod to load, my screen turns black like it's loading the mod but it just stays black and if i ALT+TAB i can move the box around but i can't click or do anything so it basically freezes my movement and black ops just stays a black screen forver until i shut down. there's no error code or anything it just freezes. sooo what's wrong?

**Comment by Arefu** [comment]
Do you have a legit non-german copy of the game on Steam?

**Comment by 2bandz** [comment]
> Do you have a legit non-german copy of the game on Steam?

no, but a bunch of my friends play it together with the same version i have and it works. and it's not german it's english

**Comment by 2bandz** [comment]
hey man i really need help i just wanna play and get memories

**Comment by lucasroyale** [comment]
I have this exact issue too

**Comment by SE2Dev** [comment]
I can't really help much unless there's an error that shows up. You could try running the game with `+set logfile 2` and checking the logs after it's been stuck on the black screen for a while.

**Comment by 2bandz** [comment]
how do i run the game with that?

**Comment by Arefu** [comment]
Yeah, see, if I remember right the game needs to be owned on Steam, not the CD version or a cracked copy.

Buy it legit, also you run it using that by either creating a shortcut or opening cmd where the game is located and typing the EXE name with the +set logfile 2 command appended at the end, just lookup command line arguments.

**Comment by 2bandz** [comment]
can you show me how i can do this method? like pictures and what not? i'm confused

**Comment by 2bandz** [comment]
sooo

**Comment by SE2Dev** [comment]
Copy the batch file that comes with game_mod, and add `+set logfile 2 +set fs_game mods/YOUR_MOD_HERE` to the end of the launch command in it, then launch that batch file. If the game black screens, wait a few moments and close it, then navigate to `GAME_DIRECTORY/players/YOU_MOD_HERE` and get the log for your mod.

**Comment by 2bandz** [comment]
okay i will try this and get back to you when i try

**Comment by 2bandz** [comment]
i think i did it right, in the game_mod.bat, i right click it then click edit, then i put the command after the command that's already in the .bat  ,, right? i tried that and the game launched normally so i loaded the mod and i'm on a black screen so i'll wait like 5 minutes before i have to log off so it's not frozen

**Comment by 2bandz** [comment]
i don't think i did, there's no log file

**Comment by SE2Dev** [comment]
Everything should be on one line in the batch file.
Did the game launch to the menu screen?

**Comment by 2bandz** [comment]
yes then i clicked mods and loaded a mod, and it gave me the black screen

**Comment by 2bandz** [comment]
when i add the line in the batch file, do i put a space where u tell me to write? or do i just immediately add the + command

**Comment by SE2Dev** [comment]
Everything should be on one line, there should be a space between the original command and the additional stuff you add.

If done correctly the game should either boot into the mod, or hang on a black screen; if it launches to the menu screen without the mod loaded, something was wrong.

You can always paste the batch file contents here too.

**Comment by 2bandz** [comment]
cd bin
launcher_ldr.exe game_mod.dll ../BlackOps.exe +set logfile 2 +set fs_game mods/zombie_trench



^^thats what is inside of my game_mod.bat

**Comment by 2bandz** [comment]
is that right?

**Comment by SE2Dev** [comment]
It should be.

**Comment by 2bandz** [comment]
i'll give it another go

**Comment by 2bandz** [comment]
so i just tried to launch it again with the command right now, and it booted up with the mod loaded, so what do i do now?

**Comment by 2bandz** [comment]
i just loaded into a game solo, and it loaded in!!! i didn't get a black screen

**Comment by 2bandz** [comment]
i think the problem fixed itself, i launched the game normally and it worked

**Comment by SE2Dev** [comment]
Very strange. I'm going to mark this issue as closed for now then.
