### ISSUE TITLE
Steam must be running

### ISSUE THREAD

**Issue by JacobAvari** [Nukem9/LinkerMod#78]
I have black ops 1 installed on steam, the files for game mod were installed correctly, but every time I attempt to run the .bat file it tells me that "Steam must be running to play this game. I have tried reinstalling and verifying my files multiple times but to no avail. If anyone knows how to fix this issue I would love to hear!

Thank you
JacobAvari

**Comment by SE2Dev** [comment]
Have you launched the game at least once via Steam?

**Comment by JacobAvari** [comment]
Yes I have

**Comment by JacobAvari** [comment]
I have managed to fix it, had to reinstall the game and all its files, thanks for the help anyways!

**Comment by SE2Dev** [comment]
Very strange. I know a handful of people have had issues like this, but there never seems to be a consistent solution.
