### ISSUE TITLE
Marking a light as non-primary

### ISSUE THREAD

**Issue by thrownewexception** [Nukem9/LinkerMod#8]
Upon further inspection all lights aren't marked as primary, which in waw at least this worked, However it seems the BO1 tools are considering them all primary. Is there a way to change this.?

**Comment by SE2Dev** [comment]
This issue does not appear to be reproducible with the information you have provided. Can you provide an example of the KVs you are using?

**Comment by thrownewexception** [comment]
@SE2Dev Sure thing
`"angles" "0 180 0"
"origin" "-319.0 321.0 162.0"
"def" "light_point_linear"
"radius" "300"
"_color" "1 1 1"
"intensity" "0.45"
"classname" "light"`

None of them have primary checked off. So they should be marked secondary, right now they're all listed as primary and goes WAY over the limit

**Comment by SE2Dev** [comment]
Where are you encountering this limit? Is it from the game, cod2rad, etc.? What is the exact error you get?

**Comment by thrownewexception** [comment]
This is a cod2map issue, "ERROR: ignoring primary light because max primary lights (255) exceeded" The lights are mostly linear points.

**Comment by SE2Dev** [comment]
What are the entity counts for your map (You can find these in radiant via Edit->Map Info).

**Comment by thrownewexception** [comment]
@SE2Dev Everything http://prntscr.com/bf8r9q

**Comment by SE2Dev** [comment]
Could you send me the *.d3dbsp file for the map?

**Comment by thrownewexception** [comment]
Would you like it after cod2rad or just after cod2map?

**Comment by SE2Dev** [comment]
After cod2map but before cod2rad

**Comment by thrownewexception** [comment]
Building now, you'll notice a slight change in info compared to the map info as I have a hide layer on until @Nukem9 can maybe sort out that max verts issue :)

**Comment by thrownewexception** [comment]
@SE2Dev https://www.justbeamit.com/mt9pf

**Comment by SE2Dev** [comment]
You have 692 lights which are not primaries, and 265 lights that are primaries.
You've exceeded the engine limit, and will need to delete ~15 primary lights.

**Comment by DidUknowiPwn** [comment]
I'm still thinking you guys are absolutely retarded.
