### ISSUE TITLE
Only shows me ERROR Code

### ISSUE THREAD

**Issue by KazyGaming** [Nukem9/LinkerMod#87]
when i try to open up the GAME_MOD launcher it just gives me an error 

"ASSERTION

d:\code\projects\c++\linkermod\components\shared\shared_utility.h(32):

*opcode == 0xE8

![Screenshot 2022-02-10 182050](https://user-images.githubusercontent.com/99422857/153461639-0b9d2e0b-e17d-47ec-8d04-26375ac977ca.png)
"

**Comment by SE2Dev** [comment]
Only the official Steam (non-German version) release is supported.

**Comment by bglopez** [comment]
I'll second this -- running against Steam installed copy (via steamcmd.exe) and seeing the same error.
