### ISSUE TITLE
Assertion Opcode 0xE8

### ISSUE THREAD

**Issue by renger08** [Nukem9/LinkerMod#91]
![issue](https://user-images.githubusercontent.com/76727260/219693926-f9e21979-950a-492a-ace4-b38417880832.png)
 please help.
I don't know what gonna do

**Comment by renger08** [comment]
Goddammit why doesn't supports cracks?
i cannot buy games from steam!

That aside, can you help and tell me how to run the DLC maps?

**Comment by SE2Dev** [comment]
Versions of the game that don't match the Steam version can have slightly different memory layouts, or modify functions in a way that we can't support.

We have no experience dealing with versions of the game other than the Steam release.
