### ISSUE TITLE
error 'opcode == 0xE9' while running batch script

### ISSUE THREAD

**Issue by krgrsebastian** [Nukem9/LinkerMod#94]
Is this maybe caused by blackops being a german version and not global? 
<img width="359" alt="Screenshot 2024-07-13 130442" src="https://github.com/user-attachments/assets/f27292be-c59e-43a8-b11b-3cf0d40a18a2">

**Comment by SE2Dev** [comment]
The German release of the game uses a different binary than other versions of the game and is therefore not supported.
